### ISSUE TITLE
Move Swerve Functionality into ChopShopLib

### ISSUE THREAD

**Issue by jeffaburke** [chopshop-166/chopshoplib#104]
We should pull this into chopshoplib at the end of the season alongside the swerve module code.

_Originally posted by @bot190 in https://github.com/chopshop-166/frc-2022/pull/9#discussion_r797201186_

**Comment by msoucy** [comment]
Closed in #133 via [c2bf32c](https://github.com/chopshop-166/chopshoplib/commit/c2bf32c7a78f34ff53ff591c6d73e02d4f3b6a0e)
