### ISSUE TITLE
PID Speed Controller

### ISSUE THREAD

**Issue by msoucy** [chopshop-166/chopshoplib#14]
Since we have a `SendableSpeedController`, it would make sense to have a derived interface that has an integrated PID controller. This would behave like an SSC, but have a couple of extra features. The wrapped version of any speed controller that has an integrated PID controller, would forward calls to that, and any other speed controller would have a WPIlib one added.

- [X] Base Interface
- [X] Spark MAX
- [x] Mock
- [ ] Talon SRX
- [x] Software PID

**Comment by msoucy** [comment]
This should probably derive from `EncodedSpeedController`.

**Comment by msoucy** [comment]
Anyone who wants to get started on this task - look up the various speed controllers that are available, and see which ones have integrated PID controllers. See how it's accessed, and see if there's any commonality.

**Comment by andrewmartin5** [comment]
I'll take a quick crack at this one

**Comment by andrewmartin5** [comment]
SparkMax PID options:
	Controlls velocity using 
		setReference(Value, RPM)
	CANPIDController(SPARKmax Controller Port)
	SetP()
	SetI()
	SetD()

**Comment by msoucy** [comment]
For posterity - we determined that it should NOT extend `EncodedSpeedController`, as there could be numerous sources of input other than an encoder. We also decided that we want `PIDSpeedController` to be an interface, and have several derived types that manage the Spark MAX, a Software PID, etc.

Did you find out if there's a way to enable/disable CAN on a Spark MAX?

**Comment by andrewmartin5** [comment]
I didn't find a way in the documentation for the CAN speed controller. There is probably a way we can simulate it though

**Comment by andrewmartin5** [comment]
Should I use the WPILib PIDController class for the software PID described above?

**Comment by msoucy** [comment]
Yes, but let's focus on the base interface and the Spark MAX one first.
