### ISSUE TITLE
Sendable Speed Controller Group

### ISSUE THREAD

**Issue by msoucy** [chopshop-166/chopshoplib#18]
Create a `SendableSpeedController` that wraps `SpeedControllerGroup`.

I wish these weren't necessary, but in the meantime this would make some of the maps easier.

**Comment by msoucy** [comment]
Idea: In `SendableSpeedController`, make a function called `group` that takes any number of `SpeedController` objects, and returns the result of wrapping a `SendableSpeedController` constructed from those objects.

**Comment by leftguardOfficial** [comment]
Making an attempt to try this

**Comment by leftguardOfficial** [comment]
After a painstaking 2 ish hours and only 5 lines of code I'm done

**Comment by msoucy** [comment]
Reopening until it's merged
