### ISSUE TITLE
Output with Brake

### ISSUE THREAD

**Issue by msoucy** [chopshop-166/chopshoplib#23]
For several years, we've had some sort of elevator that has a brake attached. In that subsystem, we usually end up having logic within the subsystem to send a value to the motor, enable/disable the brake at the appropriate times...

If we had an output that takes care of the brake automatically, then that would make the subsystem much simpler.

A `BrakedOutput` would really need these things:

- A `SendableSpeedController` for the main output
- `brake` and `release` functions to enable/disable the brake
- A speed tolerance, to only disable the brake when speed is greater than that value (Probably default to something small like `0.05`)

For consistency's sake for now, it should probably implement `SendableSpeedController`.

See our [2019](https://github.com/chopshop-166/frc-2019/blob/master/src/main/java/frc/robot/subsystems/LiftSubsystem.java#L110) and [2018](https://github.com/chopshop-166/frc-2018/blob/master/src/main/java/frc/team166/robot/subsystems/Lift.java#L264-L280) code for examples of what functionality this might contain. Note that those also use limit switches to detect if it should move at all - we can ignore this for this class, since we have a [LimitedSpeedController](https://github.com/chopshop-166/chopshoplib/blob/master/src/main/java/com/chopshop166/chopshoplib/outputs/LimitedSpeedController.java) that can take care of that and we can just compose them.

**Comment by bot190** [comment]
With #29 we can easily implement this as a new `Modifier`. No need for anything special in chopshoplib.
