### ISSUE TITLE
PID With Presets

### ISSUE THREAD

**Issue by msoucy** [chopshop-166/chopshoplib#4]
Create a PID subsystem that has presets built in to it

**Comment by andrewmartin5** [comment]
What type of presets are we talking about here?

**Comment by msoucy** [comment]
PID works by giving a PID controller a reading for what you're currently at (position or velocity), and a "setpoint" that represents what value you want to be at. It then uses those plus the coefficient values, to calculate a new value to (basically) send to speed controllers to get the value to the position we want.

The presets would be an enum containing a single value, that is used as the setpoint. The extra infrastructure in the derived class would include a function that takes one of those presets and creates a command to get to that point.

**Comment by msoucy** [comment]
Closed via #57
