### ISSUE TITLE
IDistance

### ISSUE THREAD

**Issue by msoucy** [chopshop-166/chopshoplib#6]
Create a Distance interface, for things that can report either inches or millimeters, like the Lidar and the WPIlib ultrasonic sensor.

**Comment by bot190** [comment]
We may want to look into using an existing library for this, I remember looking at the documentation for one that another team uses. It gives us the ability to do unit conversions and various dimensional analysis IIRC. I'll try to find it again when I get a chance.

**Comment by bot190** [comment]
We likely won't pull in a full unit library, especially given https://github.com/wpilibsuite/allwpilib/issues/1825

We can use the unit conversion functionality provided by WPILib in the meantime.
